<?php
$pageTemplate = str_replace("[CURRENTSEARCH]", "", $pageTemplate);
$pageTemplate = str_replace("[H1TAG]", $songsbygenre, $pageTemplate);
$pageTemplate = str_replace("[TITLE]", $songsbygenretitle, $pageTemplate);

$pageTemplate = str_replace("[KEYWORDS]", $songsbygenrekeywords, $pageTemplate);
$pageTemplate = str_replace("[DESCRIPTION]", $songsbygenredescription, $pageTemplate);

$pageTemplate = str_replace("[COMMENTS]", "", $pageTemplate);

$namesofgenres = array(
"A Capella",
"Acid",
"Acid Jazz",
"Acid Punk",
"Acoustic",
"Alternative",
"Alternative-Rock",
"Ambient",
"Anime",
"Avant-Garde",
"Ballad",
"Bass",
"Beat",
"Bebop",
"Big Band",
"Black Metal",
"Bluegrass",
"Blues",
"Booty Bass",
"Brit Pop",
"Cabaret",
"Celtic",
"Chamber Music",
"Chanson",
"Chorus",
"Christian Gangsta Rap",
"Christian Rap",
"Christian Rock",
"Classic Rock",
"Classical",
"Club-House",
"Comedy",
"Contemporary Christian",
"Country",
"Crossover",
"Cult",
"Dance",
"Dance Hall",
"Darkwave",
"Death Metal",
"Disco",
"Dream",
"Drum & Bass",
"Drum Solo",
"Duet",
"Easy Listening",
"Electronic",
"Ethnic",
"Euro-House",
"Euro-Techno",
"Eurodance",
"Fast Fusion",
"Folk",
"Folk-Rock",
"Folklore",
"Freestyle",
"Funk",
"Fusion",
"Game",
"Gangsta",
"Goa",
"Gospel",
"Gothic",
"Gothic Rock",
"Grunge",
"Hard Rock",
"Hardcore",
"Heavy Metal",
"Hip-Hop",
"House",
"Humour",
"Indie",
"Industrial",
"Instrumental",
"Instrumental Pop",
"Instrumental Rock",
"Jazz",
"Jazz & Funk",
"JPop",
"Jungle",
"Latin",
"Lo-Fi",
"Meditative",
"Merengue",
"Metal",
"Musical",
"National Folk",
"Native American",
"New Age",
"New Wave",
"Noise",
"Oldies",
"Opera",
"Other",
"Polka",
"Pop",
"Pop-Folk",
"Pop/Funk",
"Porn Groove",
"Power Ballad",
"Pranks",
"Primus",
"Progressive Rock",
"Psychedelic",
"Psychedelic Rock",
"Punk",
"Punk Rock",
"R&B",
"Rap",
"Rave",
"Reggae",
"Retro",
"Revival",
"Rhythmic Soul",
"Rock",
"Rock & Roll",
"Salsa",
"Samba",
"Satire",
"Show Tunes",
"Ska",
"Slow Jam",
"Slow Rock",
"Sonata",
"Soul",
"Sound Clip",
"Soundtrack",
"Southern Rock",
"Space",
"Speech",
"Swing",
"Symphonic Rock",
"Symphony",
"Synthpop",
"Tango",
"Techno",
"Techno-Industrial",
"Terror",
"Thrash Metal",
"Top 40",
"Trailer",
"Trance",
"Tribal",
"Trip-Hop",
"Vocal"
);

$allgenres .= "<ul id='genrespage'>";
for($k=0;$k<count($namesofgenres);$k++){

  $allgenres .= "<li><a href='http://".$_SERVER['SERVER_NAME']."/".translitIt($namesofgenres[$k]).".html'>".$namesofgenres[$k]."</a></li>";
}
$allgenres .= "</ul>";
$pageTemplate = str_replace("[CONTENT]", $allgenres, $pageTemplate);
?>